server:
  port: 8039

spring:
  application:
    name: /
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN

  #boot:
  #  admin:
  #    # Spring Boot Admin Client 客户端的相关配置
  #    client:
  #      url: https://www.bangmangma.com/boot_admin # 设置 Spring Boot Admin Server 地址
  #      instance:
  #        service-host-type: IP # 注册实例时，优先使用 IP [IP, HOST_NAME, CANONICAL_HOST_NAME]
  #        service-url: https://www.bangmangma.com

  data:
    redis:
      port: 6379
      database: 0
      host: 127.0.0.1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.225.54:3306/blog?serverTimezone=GMT
    username: root
    password: Root!!2018
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    org.mybatis.spring: ERROR

mybatis-plus:
  configuration: #sql
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    mapper-locations: classpath:com/qfedu/mapper/xml/*.xml

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true

knife4j:
  enable: false # 2.2 是否开启 Swagger 文档的 Knife4j UI 界面
  setting:
    language: zh_cn

app:
  base-url: https://www.bangmangma.com
