spring:
  application:
    name: /

  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views
      charset: UTF-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN

  profiles:
    active: prod

blog:
  swagger:
    title: 博客平台
    description: 博客平台
    version: 1.0.0
    base-package: com.mjl.blog
