server:
  port: 8039

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN

#  boot:
#    admin:
 #      # Spring Boot Admin Client 客户端的相关配置
 #     client:
 #       url: http://localhost:8050/boot_admin # 设置 Spring Boot Admin Server 地址
 #       instance:
 #         service-host-type: IP # 注册实例时，优先使用 IP [IP, HOST_NAME, CANONICAL_HOST_NAME]
 #         service-url: http://localhost:${server.port}

  data:
    redis:
      port: 6379
      database: 1
      host: 127.0.0.1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Blog?serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true

knife4j:
  enable: true # 2.2 是否开启 Swagger 文档的 Knife4j UI 界面
  setting:
    language: zh_cn

mybatis-plus:
  configuration: #sql??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/qfedu/mapper/xml/*.xml

app:
  base-url: http://localhost:${server.port}
